### PR TITLE
Bug fixes for notifySetpointsStop and cmdVelocityWorld

### PR DESCRIPTION
**Pull request by MauroPfister**
- Add `cmdVelocityWorld` code in `crazyswarm_server.cpp`
- Add `notifySetpointsStop` code in `crazyswarm_server.cpp`
- Fix typo and add `groupMask` argument to `notifySetpointsStop` service call in `crazyflie.py`
- Update `crazyflie_ros` submodule

This is my first PR, please let me know if I screwed up anything ;)

### CODE REVIEW

**Comment by jpreiss** [comment]
Looks good! I will test your changes on our system on Weds or Thurs.

**Comment by jpreiss** [comment]
@MauroPfister it looks like you are adding commits for your own experiments to this branch. They become part of the PR. Please create a new branch for that work and revert the changes here.

PRs reference a branch name, not a commit. This is confusing at first but it is desirable for code review cycles.

**Comment by MauroPfister** [comment]
Oh I am sorry, was not aware of this! Shall I revert the commits or delete them. I know that deleting commits is usually not a good option for a public repo, but if only you pulled that branch it might be cleaner?

**Comment by jpreiss** [comment]
Just revert them - I will squash this all into one commit anyway.

**Comment by MauroPfister** [comment]
Hope this is okay now. Thanks for the patience :)

**Comment by jpreiss** [comment]
Thank you! Your changes work in our lab too :)

**Pull request merged**
